[project]
name = "app-fastapi-astra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.124.4",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.45",
]
